### ISSUE TITLE
Elimina los archivos que no se usan

### ISSUE THREAD

**Issue by oneeyedman** [constanza-sosa/m2-2.9-ej04#1]
@constanza-sosa: En este proyecto no usas gulp/node así que debes borrar los archivos que crea lanzar por error un `npm install`.

**Comment by constanza-sosa** [comment]
Intente poner el Es lint con, que decía que era con un npm install, pero no lo debi hacer bien. Lo borro y eso lo añado el lunes, porque en el proyecto si me funciona, pero en mas archivos, no lo consigo :)
